version: "3.8"

services:
  magicdoor-portal-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: magicdoor-portal-frontend:dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true
