version: "3.8"
services:
  magicdoor-portal-frontend:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0"]

  magicdoor-portal-frontend-tests:
    build:
      context: .
      dockerfile: ./.docker/dev/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "test"]
