name: Docker Image CI - Build Prod

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: magicdoor-portal-frontend

jobs:
  build-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Lowercase repository name
        id: repo-name
        run: echo ::set-output name=repo::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/prod/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo-name.outputs.repo }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ steps.repo-name.outputs.repo }}/${{ env.IMAGE_NAME }}:latest
