name: Docker Image CI

on: push

env:
  IMAGE_NAME: magicdoor-portal-frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/dev/Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Run the Docker container
        run: docker run --name my-container -d ${{ env.IMAGE_NAME }}:latest

      - name: Run tests in the Docker container
        run: docker exec my-container npm test

  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/prod/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
